# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8fe3e538-d29b-4eed-9f58-86716a49dc8c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8fe3e538-d29b-4eed-9f58-86716a49dc8c".device = "/dev/disk/by-uuid/8fe3e538-d29b-4eed-9f58-86716a49dc8c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8037-E1F9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-769370cf-598d-44a8-a737-92503b44a377"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
